apiVersion: v1
kind: Service
metadata:
  name: superno-service
spec:
  selector:
    app: superno
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  - protocol: TCP
    port: 81
    targetPort: 5173
  type: LoadBalancer
